apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: ##SECRETS_PROVIDER_CLASS_NAME##
  namespace: ##POD_IDENTITY_NAMESPACE##
spec:
  provider: azure
  secretObjects:
  - secretName: tls-csi
    type: kubernetes.io/tls
    data:
    - objectName: tls.crt
      key: tls.crt
    - objectName: tls.key
      key: tls.key
  parameters:
    usePodIdentity: "true"
    keyvaultName: ##KEYVAULT_NAME## # replace with your own keyvault
    objects:  |
      array:
        - |
          objectName: tls-crt
          objectAlias: tls.crt
          objectType: secret
        - |
          objectName: tls-key
          objectAlias: tls.key
          objectType: secret
    tenantId: ##AAD_TENANT_ID## # replace with tenant id